### PR TITLE
Fix broken carrier accounts unit tests

### LINKED ISSUE #2074: Unit tests failing
We have a number of JS unit tests failing in the latest `develop`. Running `npm run test-client`, I see:
image

### PR DESCRIPTION
**Pull request by Ferdev**
Closes #2074

### CODE REVIEW

**Comment by harriswong** [comment]
👀

File: client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/index.js [hunk 1]
```diff
@@ -69,7 +66,7 @@ CarrierAccounts.propTypes = {
 	siteId: PropTypes.number.isRequired,
 	carriers: PropTypes.arrayOf(
 		PropTypes.shape( {
-			id: PropTypes.string.isRequired,
+			id: PropTypes.string,
```
Comment (harriswong) [inline client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/index.js:69]: How come `id` is no longer required?

Comment (Ferdev) [reply client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/index.js:69]: It's because the only property always consumed by the frontend is the carrier name, which is called `carrier` and it's the only one required right now.

**Comment by Ferdev** [comment]
> I got the following when i run `npm run test`, I understand this is outside of fixing unit tests, we can create a separate issue if it's too much effort to address.

I'm gonna fix all the linting issues related to carrier accounts, just to keep all the changes in the current scope, but I'll leave the others for another issue.

**Comment by Ferdev** [comment]
I've fixed all carrier account related linting issues that can be fixed. There're a few of them which are false positives due to a bug in eslint. I've created issue #2097 to fix all these problems.

File: client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/index.js (hunk 1 above)
Comment (harriswong) [reply client/extensions/woocommerce/woocommerce-services/views/carrier-accounts/index.js:69]: Oh I see. Thanks!
