### PR TITLE
Extract WC_Connect_TaxJar_Integration::backup_existing_tax_rates() for re-usability - Fix/issue 2523

### LINKED ISSUE #2523: Tax rates backup before CA taxes deletion
## Description
Discussed here: https://github.com/Automattic/woocommerce-services/pull/2522

Before deleting the CA tax rates, backup all the tax rates in the table to a CSV file.

We can extract the `WC_Connect_TaxJar_Integration->backup_existing_tax_rates()` method in a separate class (without the `TRUNCATE`) so that it can be shared.

### PR DESCRIPTION
**Pull request by dustinparker**
## Description

Extracted the `WC_Connect_TaxJar_Integration::backup_existing_tax_rates()` to the `WC_Connect_Functions` class as a static method so it can be used in other classes as well.

### Related issue(s)

Fixes #2523 
### Steps to reproduce & screenshots/GIFs

1. Add a few tax rates under WC > Settings > Tax > Standard Rates
2. Go to WC > Settings > Tax > Tax options and enable Automated Taxes
3. The tax rates you entered in step 1 should be backed up in a CSV file under `/wc-content/uploads/`
4. WC > Settings > Tax > Standard Rates should show be cleared of all previously entered tax rates.

### Checklist

- [ ] unit tests

- [x] `changelog.txt` entry added

### CODE REVIEW

File: classes/class-wc-connect-functions.php [hunk 1]
```diff
@@ -95,5 +95,130 @@ public static function user_can_manage_labels() {
...
+		 */
+		public static function backup_existing_tax_rates() {
+			global $wpdb;
+
+			// Export Tax Rates
+			$rates = $wpdb->get_results(
+				$wpdb->prepare(
+					"SELECT * FROM {$wpdb->prefix}woocommerce_tax_rates
+			ORDER BY tax_rate_order
+			LIMIT %d, %d
```
Comment (iyut) [inline classes/class-wc-connect-functions.php]:
```suggestion
			        ORDER BY tax_rate_order
			        LIMIT %d, %d
```
I think this can be a bit tidier.

File: classes/class-wc-connect-functions.php [hunk 2]
```diff
@@ -95,5 +95,130 @@ public static function user_can_manage_labels() {
...
+					echo '0';
+				}
+
+				echo ',';
+
+				echo "\n";
+			} // End foreach().
+
+			$csv = ob_get_contents();
+			ob_end_clean();
```
Comment (iyut) [inline classes/class-wc-connect-functions.php]:
```suggestion
			$csv = ob_get_clean();
```
Is there any reason to separate `ob_get_contents()` and `ob_end_clean()`? Perhaps we can make it shorter?

**Review by iyut — APPROVED** [review]
The changes does create a csv for the backup in `wp-content/uploads` and remove current standard tax list. LGTM!
