### PR TITLE
Ignore county when country is UK for automated tax

### LINKED ISSUE #1600: Tax Rates fail for UK addresses when adding counties
Reported in:

1942485-zen
14189124-hc
2524915-zen
2537618-zen

## Summary

For all addresses in the UK, the tax rate on the front end will display as 0.00 if a county is entered that actually exists.

## Steps to replicate

1. Install/Activate/Connect Jetpack
2. Install/Activate [WooCommerce Services](https://wordpress.org/plugins/woocommerce-services/)
3. Set your store address to have a UK address (e.g. 63 Elford Crescent, Plympton, Plymouth, UK, PL74BT)
4. Set your tax rate settings to "Enable Automated Taxes"
5. On the front end, add a product to the cart and proceed to checkout
6. On the billing address section, use any of the following address:
 * 2 Chestnut Hall Avenue, Maghaberry, Moira, County Armagh, BT67 0GG
 * 40 Whitehall Way, Rockingham, Rotherham, South yorkshire, S61 4HW 
 * 19 Carisbrooke Close, EASTBOURNE, East Sussex, BN23 8EQ
7. Notice on the checkout page that VAT is showing up as 0.00
8. Complete the order.
9. Notice that the postcode for that order has been added as a tax rate under **WooCommerce > Settings > Tax > Standard Rates**

Here's are some screenshots to illustrate that better:

**Front-end Checkout**

https://cld.wthms.co/4Jes3J
Full Image: https://cld.wthms.co/4Jes3J+

**Tax Settings after checkout**

https://cld.wthms.co/p9KLqN
Full Image: https://cld.wthms.co/p9KLqN+

## Additional Notes

@mikkamp managed to narrow things down even further to the `county` field. When using "Bogus" as the county, tax rates work as expected. When a legitimate county is used (e.g. "County Armagh"), tax rates are borked and multiple entries are created in the standard rates section.

### PR DESCRIPTION
**Pull request by harriswong**
When country is UK, the shipping address allow county to be a text field. This text field does not respect a "state code" format (ie. 2 letters). This creates a problem with WooCommerce core's tax code. While the core team is working on the issue, we are going to patch this by disabling county in the tax field for automated tax. County is optional and this change will not break tax rate.

### Notes
County is optional field for UK. https://developers.taxjar.com/api/reference/#post-calculate-sales-tax-for-an-order
image
By removing the county field, WooCommerce core will insert this entry as `*` which can match any county.
image

### To test
1. Set store address to an UK address, https://localhost/wp-admin/admin.php?page=wc-settings&tab=general. We can use the ones from the issue, (e.g. 63 Elford Crescent, Plympton, Plymouth, UK, PL74BT)
2. Add an item, go to the checkout page. Use shipping addresses:
- 2 Chestnut Hall Avenue, Maghaberry, Moira, County Armagh, BT67 0GG
- 40 Whitehall Way, Rockingham, Rotherham, South yorkshire, S61 4HW
- 19 Carisbrooke Close, EASTBOURNE, East Sussex, BN23 8EQ
3. Refresh the checkout page a few times
4. Verify `VAT` shows up as 20% tax of the product cost
5. Go to https://localhost/wp-admin/admin.php?page=wc-settings&tab=tax&section=standard, there should only be 1 entry per address. 

Closes #1600

### CODE REVIEW

File: classes/class-wc-connect-taxjar-integration.php [hunk 1]
```diff
@@ -868,6 +868,10 @@ public function calculate_tax( $options = array() ) {
 				'to_city' => $to_city,
 			);
 
+			if ( $to_country === 'GB') {
```
Comment (superdav42) [inline classes/class-wc-connect-taxjar-integration.php]: Use Yoda conditions you must.

Comment (harriswong) [reply classes/class-wc-connect-taxjar-integration.php]: Fixed!
