### PR TITLE
Fix Error always block checkout when using WC Blocks

### LINKED ISSUE #2683: Incompatibility with Checkout Block. Occasionally throw error ("ZIP Code does not match the selected state.")
When using the checkout block or a block based theme like Blockbase or Tsubaki while [WooCommerce Shipping & Tax](https://woocommerce.com/products/shipping/?aff=10486&cid=1131038) (WCS&T) is active, using a valid combination of state + ZIP will occasionally produce the following error for customers:

```
ZIP Code does not match the selected state.
```

### Steps to reproduce : 

1. Enable WooCommerce.
2. Install/activate/configure [Jetpack](https://woocommerce.com/products/jetpack/?aff=10486&cid=1131038).
3.Install/activate/configure [WooCommerce Shipping & Tax](https://woocommerce.com/products/shipping/?aff=10486&cid=1131038) to provide automated taxation.
4. Modify the theme template so that it uses the Checkout Block instead of the checkout shortcode.
5. Try to make a purchase using the Checkout Block with any payment method (e.g. [Check Payments](https://woocommerce.com/document/cheque/))
6. Encounter the error.

Note for step 6: this may require using a guest checkout, clearing the browser cache, and/or attempting multiple different postcode/state combinations, as it's finicky if a postcode is used that's been validated before. Here are some that I use that can help with debugging:

Sacramento, California, US 95816
Beverly Hills, California, US 90210
Vinita, Oklahoma, US 74301
New York, New York, US 10001
Oxford, Mississippi, US 38655
Como, Mississippi, US 38619
Horn Lake, Mississippi, US 38637

This issue is related to this [WC Blocks issue #10847](https://github.com/woocommerce/woocommerce-blocks/issues/10847)

### PR DESCRIPTION
**Pull request by iyut**
## Description
Fixing a compatibility issue with WC Blocks where User cannot checkout because it always throw an error on checkout page that using WC Blocks. In this PR I remove the unneeded function and hooks. Because I dont see the point on having that hook and also removing the hook seems fixing the issue.

### Related issue(s)

Fixes #2683 

### Steps to reproduce & screenshots/GIFs

1. Enable WooCommerce.
2.Install/activate/configure [WooCommerce Shipping & Tax](https://woocommerce.com/products/shipping/?aff=10486&cid=1131038) to provide automated taxation.
3. Automate the tax.
3. Change the cart page and checkout page to use WooCommerce cart and checkout blocks.
4. Try to make a purchase using the Checkout Block with any payment method (e.g. [Check Payments](https://woocommerce.com/document/cheque/))
5. Use this address : Beverly Hills, California, US 90210. Then change the state from California to any other states.
6. The zip code error will show : `The provided postcode / ZIP is not valid`.
7. Change the state back to California, the error will not show and checkout will be submitted.

### Checklist

- [ ] unit tests

- [x] `changelog.txt` entry added
- [x] `readme.txt` entry added

### CODE REVIEW

File: classes/class-wc-connect-cart-validation.php [hunk 1]
```diff
@@ -11,13 +11,6 @@ class WC_Connect_Cart_Validation {
 	 */
 	private $current_package;
 
-	/**
-	 * Register actions when required instead of using constructor.
-	 */
-	public function register_actions() {
-		add_action( 'woocommerce_store_api_cart_errors', [ $this, 'add_api_cart_errors' ], 10, 2 );
```
Comment (Abdalsalaam) [inline classes/class-wc-connect-cart-validation.php]: do you have any idea why its added in the first place ? do you think we should check this [commit](https://github.com/Automattic/woocommerce-services/commit/47ab8331da19b100f9a8b01e37546b9b9ad2f697)

Comment (iyut) [reply classes/class-wc-connect-cart-validation.php]: It was added back in the day when WooCommerce ( ver. 6.4.0 ) still need to use WooCommerce Blocks ( ver. 7.3.0 ) plugin to display the error. But upon my testing on the latest WooCommerce this action is seems not needed anymore. It can check the error by itself.

That's why I'm proposing to remove this action. But after having a second thought. I'll add this action again and add some condition to make this plugin compatible with older WooCommerce and WooCommerce Blocks plugin.

Comment (Abdalsalaam) [reply classes/class-wc-connect-cart-validation.php]: it looks good, I tested it and the issue fixed

**Review by Abdalsalaam — APPROVED** [review]

**Comment by ralucaStan** [comment]
Is there anything that is blocking this PR from being merged? We have incoming reports of people being affected by this issue.

**Comment by iyut** [comment]
@samnajian , is that OK if we merge this PR with E2E tests failing? Or do you mind to review the fixes for E2e tests [PR](https://github.com/Automattic/woocommerce-services/pull/2681)? 
Once E2E tests is approved and merged to `trunk` branch, then I can merge the `trunk` branch to this PR and merge this fixes.

**Comment by iyut** [comment]
> Is there anything that is blocking this PR from being merged?

@ralucaStan , at the moment, we're blocked with the failed E2E tests. We will try to speed up this [PR review](https://github.com/Automattic/woocommerce-services/pull/2681) and then merge this fix.

**Comment by samnajian** [comment]
> @samnajian , is that OK if we merge this PR with E2E tests failing? Or do you mind to review the fixes for E2e tests https://github.com/Automattic/woocommerce-services/pull/2681? Once E2E tests is approved and merged to `trunk` branch, then I can merge the `trunk` branch to this PR and merge this fixes.

@iyut The e2e PR is approved, please rebase it into this branch before merging.
