### PR TITLE
Fix TOS-only banner - remove connection flow

### LINKED ISSUE #1188: Show TOS-only banner for users who are already connected to Jetpack
Steps to repro:

1. Ensure Jetpack is installed + connected
2. Uninstall all WooCommerce and WooCommerce Services things. Remove all DB options, etc
3. Go through WC wizard using a US locale, and make sure to enable Stripe + enter your email to create an account automatically
4. After you finish the wizard, go to the plugins page
5. See this banner:

screen shot 2017-10-13 at 8 28 18 am

This banner directs users to connect to Jetpack. It's incorrect because in this case the user is already connected to Jetpack.

Instead, we should display this banner:

tos-only-banner

This banner should save the TOS_accepted option.

### PR DESCRIPTION
**Pull request by jeffstieler**
Fixes #1188.

This PR seeks to restore the TOS-only banner (with new verbiage) that doesn't redirect to WPCOM.

It also adds the "should display" logic to the TOS-only banner, so it doesn't display on every admin screen. (The idea being that will help with "nag" complaints)

To test:
* Ensure a connected Jetpack
* Either remove the WCS plugin (and options), or set `wc_connect_options.tos_accepted` to `0`
* Verify that on NUX banner pages (plugins, WC pages) the TOS-only banner shows
* Verify that clicking "connect" dismisses the banner and sets `wc_connect_options.tos_accepted` to `1` and doesn't send you to WPCOM

### CODE REVIEW

File: classes/class-wc-connect-nux.php [hunk 1]
```diff
@@ -546,6 +545,44 @@ public function show_banner_after_connection() {
...
+
+			$country = WC()->countries->get_base_country();
+			/* translators: %s: list of features, potentially comma separated */
+			$description_base = __( "WooCommerce Services is almost ready to go! Once you connect your store you'll have access to %s.", 'woocommerce-services' );
+			$feature_list     = $this->get_feature_list_for_country( $country );
+
+			$this->show_nux_banner( array(
+				'title'          => __( 'Connect your store to activate WooCommerce Services', 'woocommerce-services' ),
+				'description'    => esc_html( sprintf( $description_base, $feature_list ) ),
+				'button_text'    => __( 'Connect', 'woocommerce-services' ),
```
Comment (dechov) [inline classes/class-wc-connect-nux.php]: The verbiage here in title, description, and button_text still evokes something more involved than flipping the TOS bit — as in, if they've already connected their store to Jetpack, so what are they connecting it to now?

Comment (jeffstieler) [reply classes/class-wc-connect-nux.php]: This is the same verbiage as introduced in https://github.com/Automattic/woocommerce-services/pull/1177.

In this scenario, the user is in effect connecting their store to WooCommerce Services (SaaS layer). Since they're now opting into WCS, more of the Jetpack TOS apply to them, so we redisplay those terms.

Comment (dechov) [reply classes/class-wc-connect-nux.php]: As https://github.com/Automattic/woocommerce-services/issues/1188 (being fixed) says,
> This banner directs users to connect to Jetpack.

Even if it doesn't say "Connect to Jetpack" in this case, why overload the term? I understand that we want to redisplay the terms, but in the event we do want the term "Connect" for accepting WCS terms, we should at least clarify that they're connecting to not-Jetpack in my opinion. cc @v18

Comment (jeffstieler) [reply classes/class-wc-connect-nux.php]: @dechov @v18 can we agree to discuss the wording separate from reviewing this bug fix PR?

Comment (dechov) [reply classes/class-wc-connect-nux.php]: Yes! Sorry, I had missed the context of there being an actual bug separate from the verbal communication. Disregard ^^

File: classes/class-wc-connect-nux.php [hunk 2]
```diff
@@ -471,26 +474,22 @@ public function show_banner_before_connection() {
...
 			$button_text    = __( 'Connect', 'woocommerce-services' );
-			$banner_title   = __( 'Connect your store to activate WooCommerce Services', 'woocommerce-services' );
+			$banner_title   = __( 'Connect Jetpack to activate WooCommerce Services', 'woocommerce-services' );
 			$image_url      = plugins_url( 'images/wcs-notice.png', dirname( __FILE__ ) );
 
 			switch ( $jetpack_status ) {
 				case self::JETPACK_NOT_INSTALLED:
 					$button_text  = __( 'Install Jetpack and connect', 'woocommerce-services' );
-					$banner_title = __( 'Connect Jetpack to activate WooCommerce Services', 'woocommerce-services' );
+
```
Comment (v18) [inline classes/class-wc-connect-nux.php]: Accidental extra line?

Comment (jeffstieler) [reply classes/class-wc-connect-nux.php]: Yep - going to rewrite that commit to remove it.

Comment (jeffstieler) [reply classes/class-wc-connect-nux.php]: Done in d5617a2.

File: classes/class-wc-connect-nux.php [hunk 3]
```diff
@@ -546,6 +545,44 @@ public function show_banner_after_connection() {
...
+				'title'          => __( 'Connect your store to activate WooCommerce Services', 'woocommerce-services' ),
+				'description'    => esc_html( sprintf( $description_base, $feature_list ) ),
+				'button_text'    => __( 'Connect', 'woocommerce-services' ),
+				'button_link'    => add_query_arg( array(
+					'wcs-nux-tos' => 'accept',
+				) ),
+				'image_url'      => plugins_url(
+					'images/wcs-notice.png', dirname( __FILE__ )
+				),
+				'should_show_jp'    => true,
```
Comment (v18) [inline classes/class-wc-connect-nux.php]: Question: do we want to display the JP logo in this banner? We didn't used to display it here, and I'm not really sure it's needed.

File: classes/class-wc-connect-nux.php (hunk 1 above)
Comment (v18) [reply classes/class-wc-connect-nux.php]: Agree with verbiage questions - opened separate issue for it here: https://github.com/Automattic/woocommerce-services/issues/1192#issue-265428329

Comment (dechov) [reply classes/class-wc-connect-nux.php]: Thanks — and 👍  @jeffstieler for distinguishing urgency & prioritization of different matters

File: classes/class-wc-connect-nux.php (hunk 3 above)
Comment (jeffstieler) [reply classes/class-wc-connect-nux.php]: Whoops! Good catch - that was a copy-paste error I made.

Comment (jeffstieler) [reply classes/class-wc-connect-nux.php]: Fixed in https://github.com/Automattic/woocommerce-services/pull/1190/commits/60954b9281d0d80700250276a076bd42663cf7ef.

**Comment by v18** [comment]
Looks like the bug still exists. Re-testing to see what's going wrong.
