### PR TITLE
Fix too many rate requests

### LINKED ISSUE #1360: Rates are calculated when WP-Admin and unrelated AJAX requests are received
To reproduce:
* log in as an admin
* add items to the cart
* make sure WooCommerce remembers a checkout address for your user that is a valid rates address
* open WP-Admin
* enable debug mode in `WooCommerce > Settings > Shipping > Shipping Options`
* rates request is sent to the server in the background

This is making the Store on WP.com almost unusable since the requests are timing out when requesting rates.

### PR DESCRIPTION
**Pull request by marcinbot**
Fixes #1360 

* Copied the solution from #1308 to skip the requests when not on the checkout page or the request is a Jetpack request
* ~~added rates response memory caching - requests can attempt to calculate rates more than once and our code would send the rates request every time for this~~

To test:
* enable debug mode in `WooCommerce > Settings > Shipping > Shipping Options` to ensure that rates are not cached
* WP Admin requests and non-checkout AJAX requests should not generate a rate request - this can be checked either by monitoring the server console output or placing a debug breakpoint in `class-wc-connect-shipping-method.php`
* checkout rates should display and update when cart contents/address are updated
* ~~only one rates request should be sent per WP request - added a debug message to monitor when a request has been retrieved from cache~~

### CODE REVIEW

**Comment by jeffstieler** [comment]
Can you provide more detailed testing instructions?

I'm unable to reproduce this on my local VVV setup, as well as a Poopy.life test install. Note: without automated taxes enabled.

I'll test with automated taxes on Poopy.life and report back.

File: classes/class-wc-connect-shipping-method.php [hunk 1]
```diff
@@ -262,6 +297,25 @@ private function add_fallback_rate( $service_settings ) {
...
+
+			// Skip during REST API or XMLRPC requests
+			if ( defined( 'REST_REQUEST' ) || defined( 'REST_API_REQUEST' ) || defined( 'XMLRPC_REQUEST' ) ) {
+				return;
+			}
+
+			// Skip during Jetpack REST API proxy requests
+			if ( isset( $_GET['rest_route'] ) && isset( $_GET['_for'] ) && ( 'jetpack' === $_GET['_for'] ) ) {
+				return;
+			}
```
Comment (jeffstieler) [inline classes/class-wc-connect-shipping-method.php]: Rather than directly copy-paste this code, can we move it somewhere it can be shared, avoiding duplication?

File: classes/class-wc-connect-shipping-method.php [hunk 2]
```diff
@@ -301,37 +355,19 @@ public function calculate_shipping( $package = array() ) {
...
+			);
+			$response_body = wp_cache_get( $cache_key );
+			if ( false !== $response_body ) {
+				$this->debug( 'Rates response retrieved from cache' );
+			} else {
+				$response_body = $this->api_client->get_shipping_rates( $services, $package, $custom_boxes, $predefined_boxes );
+				if ( $this->check_and_handle_response_error( $response_body ) ) {
+					return;
+				}
+				wp_cache_set( $cache_key, $response_body, '', 3600 );
```
Comment (jeffstieler) [inline classes/class-wc-connect-shipping-method.php]: I'd rather us separate the addition of `/wp-admin` cart detection and shipping rate request caching so they can be tested/vetted in isolation. Can you put these changes in to a new PR?

**Comment by jeffstieler** [comment]
Forgot to comment - the changes work well to prevent unnecessary rates requests in the admin. There are some organizational changes I'd like to see made, as the inline comments indicate.
