### PR TITLE
Replace string 20 to number 18 to match gridicons requirements

### LINKED ISSUE #2104: UPS packages not added to the dropdown in the create shipping label modal
When creating a shipping label for an international address, any UPS packages selected won't appear in the package selection dropdown. A Javascript error occurs after accepting the customer address.

### Steps to reproduce the issue

First of all, you need to have enabled UPS in your test site.

1. Purchase a product using an international address. I used one from Spain.

2. Go to the order's page, and create a new shipping label.

3. When you're asked to validate the customer address, press "Use address as entered".

image

4. In the packaging step, press on "Select a package type", and select any of the UPS packages.

5. Only non-UPS packages will appear in the dropdown. If no other packages have been selected, the dropdown won't appear at all.

You should get a Javascript error after the customer address is validated:

```
warning.js:33 Warning: Failed prop type: Invalid prop `size` of type `string` supplied to `t`, expected `number`.
    in t (created by PackageSelect)
    in PackageSelect (created by Localized(PackageSelect))
    in Localized(PackageSelect) (created by Connect(Localized(PackageSelect)))
    in Connect(Localized(PackageSelect)) (created by PackageInfo)
    in div (created by PackageInfo)
    in PackageInfo (created by Localized(PackageInfo))
    in Localized(PackageInfo) (created by Connect(Localized(PackageInfo)))
    in Connect(Localized(PackageInfo)) (created by PackagesStep)
    in div (created by PackagesStep)
    in div (created by FoldableCard)
    in div (created by Card)
    in Card (created by CompactCard)
    in CompactCard (created by FoldableCard)
    in FoldableCard (created by Localized(FoldableCard))
    in Localized(FoldableCard) (created by StepContainer)
    in StepContainer (created by Localized(StepContainer))
    in Localized(StepContainer) (created by PackagesStep)
    in PackagesStep (created by Localized(PackagesStep))
    in Localized(PackagesStep) (created by Connect(Localized(PackagesStep)))
    in Connect(Localized(PackagesStep)) (created by LabelPurchaseModal)
    in div (created by LabelPurchaseModal)
    in div (created by LabelPurchaseModal)
    in div (created by LabelPurchaseModal)
    in div (created by DialogBase)
    in div (created by ModalPortal)
    in div (created by ModalPortal)
    in ModalPortal (created by Modal)
    in Modal (created by DialogBase)
    in DialogBase (created by Dialog)
    in MomentProvider (created by Connect(MomentProvider))
    in Connect(MomentProvider)
    in Provider
printWarning	@	warning.js:33
warning	@	warning.js:57
checkPropTypes	@	checkPropTypes.js:54
validatePropTypes	@	react.development.js:1714
createElementWithValidation	@	react.development.js:1813
React$$1.createElement	@	react-hot-loader.development.js:2875
PackageSelect	@	package-select.js:112
renderWithHooks	@	react-dom.development.js:14826
mountIndeterminateComponent	@	react-dom.development.js:17506
beginWork	@	react-dom.development.js:18630
beginWork$1	@	react-dom.development.js:23211
performUnitOfWork	@	react-dom.development.js:22189
workLoopSync	@	react-dom.development.js:22162
performSyncWorkOnRoot	@	react-dom.development.js:21788
(anonymous)	@	react-dom.development.js:11112
unstable_runWithPriority	@	scheduler.development.js:653
runWithPriority$1	@	react-dom.development.js:11062
flushSyncCallbackQueueImpl	@	react-dom.development.js:11107
flushSyncCallbackQueue	@	react-dom.development.js:11095
discreteUpdates$1	@	react-dom.development.js:21925
discreteUpdates	@	react-dom.development.js:1072
dispatchDiscreteEvent	@	react-dom.development.js:4169

### PR DESCRIPTION
**Pull request by harriswong**
Closes #2104

To test
1. You can setup WCS to have empty packages in your list. Or you can modify [this line](https://github.com/Automattic/woocommerce-services/blob/develop/client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/packages-step/package-select.js#L110) to `{ true || 0 === totalPackagesCount ? (` so that the `div` is forced to show.
2. Make sure no errors in console.

### CODE REVIEW

File: client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/packages-step/package-select.js [hunk 1]
```diff
@@ -109,7 +109,7 @@ const PackageSelect = props => {
 			</div>
 			{ 0 === totalPackagesCount ? (
 				<div className="packages-step__no-packages">
-					<Gridicon icon="product" size="20" />
+					<Gridicon icon="product" size={18} />
```
Comment (harriswong) [inline client/extensions/woocommerce/woocommerce-services/views/shipping-label/label-purchase-modal/packages-step/package-select.js:112]: `20` is not allowed in the Girdicons `size` settings.
>  error  Gridicon size should be one of recommended sizes: 12, 18, 24, 36, 48, 54, 72
Tried using both `18` and `24`. 
`18` looks like 
image

`24` looks like 
image

18 seems to be closer to the original 20. So i am using 18 here.
