### PR TITLE
Fix/issue 2371 - Removed refunded line items from the shipping label creation modal

### LINKED ISSUE #2371: Refunded line items present in package selection
Reported in 3807410-zen

When an order contains refunded items, the items are still displayed in the "items to fulfill" table of the label purchase interface e.g.:
see screen shot
https://d.pr/i/fcks2C

Is this expected behavior?

### PR DESCRIPTION
**Pull request by dustinparker**
## Description

Removed refunded line items from the shipping label creation modal because refunded items should not be shipped.
### Related issue(s)

Closes #2371 
### Steps to reproduce & screenshots/GIFs

1. Add 4 Beanies to cart and checkout.
2. Open the order you just placed.
3. Notice the Shipping Label meta box shows 4 items that need to be fulfilled (similar to screenshot).
Meta Box - After
4. If you click "Create Shipping Label" and go to the Packaging tab, you'll see all 4 items ready to be packed (similar to screenshot).
Modal - After
5. Close the modal and scroll down to the line item overview.
6. Click the "Refund" button and refund 2 of the Beanies.
7. Once the page reloads you'll see in the Shipping Label meta box that only 2 items are needing fulfilled.
8. If you click "Create Shipping Label" and go to the Packaging tab, you'll see only 2 items ready to be packed.

### Checklist

- [ ] unit tests

- [x] `changelog.txt` entry added

### CODE REVIEW

**Review by iyut — APPROVED** [review]
The changes does reduce the item quantity with the refunded item. Looks good to me!

File: classes/class-wc-connect-shipping-label.php [hunk 1]
```diff
@@ -518,7 +520,7 @@ public function meta_box( $post, $args ) {
 			$order                   = wc_get_order( $post );
 			$order_id                = WC_Connect_Compatibility::instance()->get_order_id( $order );
 			$items                   = array_filter( $order->get_items(), array( $this, 'filter_items_needing_shipping' ) );
-			$items_count             = array_reduce( $items, array( $this, 'reducer_items_quantity' ), 0 );
+			$items_count             = array_reduce( $items, array( $this, 'reducer_items_quantity' ), 0 ) - absint( $order->get_item_count_refunded() );
```
Comment (harriswong) [inline classes/class-wc-connect-shipping-label.php:543]: It seems like this could be a good candidate to enhance our test coverage, especially this is related to refund. What do you think about adding a test case to our existing `tests/php/test-class-wc-connect-shipping-label.php`? Or is this function hard to test?

Comment (dustinparker) [reply classes/class-wc-connect-shipping-label.php:543]: I'll look into adding a test to this.

Comment (harriswong) [reply classes/class-wc-connect-shipping-label.php:543]: Thank you!!
